POST http://localhost:5000/signup
Content-Type: application/json

{
    "fname":"sample",
    "email":"sample@gmail.com",
    "password":"sample1234"
}
###
GET http://localhost:5000/data

###

POST http://localhost:5000/login
Content-Type: application/json

{
   "email":"sample@gmail.com",
   "password":"sample1234"
}